
name: 28544_test

on:
  push:
    branches: [master]

jobs:
  checkTests:
    name: check if test file exists
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check for openCV_test.py
        id: check
        run: |
          if [ -f openCV_test.py ]; then
            echo "Test file found."
            echo "error_exists=false" >> $GITHUB_OUTPUT  # Set output variable
          else
            echo "Test file 'openCV_test.py' not found!" 1>&2
            echo "Test file not found!" > napaka.txt     # Save error to file
            echo "error_exists=true" >> $GITHUB_OUTPUT   # Set output variable
          fi

      - name: upload napaka.txt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt

  runTests:
    name: run tests
    needs: checkTests
    if: needs.checkTests.outputs.error_exists == 'false' 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pythonVersion: [3.8, 3.10]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: download napaka.txt
        uses: actions/download-artifact@v4
        with:
          name: napaka
        continue-on-error: true

      - name: set up python
        uses: actions/setup-python@v4
        with:
          pythonVersion: ${{ matrix.python-version }}

      - name: dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run tests
        run: |
          if grep -q "not found" napaka.txt; then
            echo "Error found in napaka.txt. Exiting."
            exit 1  # Fail the job if there's an error
          else
            echo "Running unit tests..."
                  if ! python -m unittest openCV_test.py; then
                    echo "Unit tests failed. Exiting."
                    exit 1  # Fail the job if tests fail
                  fi
          fi
