name: 28544_deploy

on:
  workflow_run:
    workflows: ["28544_test"]
    types: ["completed"]

jobs:
  buildAndPush:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your project code
      - name: checkout
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub using secrets
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: docker build
        run: |
          docker build -t tilcica/opencv-project:latest .

      # Step 4: Push Docker image to DockerHub
      - name: docker push
        run: |
          docker push tilcica/opencv-project:latest
