name: 28544_deploy

on:
  workflow_run:
    workflows: ["28544_test"]
    types: [completed]

jobs:
  build-and-push:
    name: docker image
    runs-on: ubuntu-latest
    needs: runTests  # Ensures this only runs after tests pass

    # Matrix example: two tags (e.g. latest and v1)
    strategy:
      matrix:
        tag: [latest, v1]

    steps:
      # Step 1: Checkout your project code
      - name: checkout
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub using secrets
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build Docker image
      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/opencv-project:${{ matrix.tag }} .

      # Step 4: Push Docker image to DockerHub
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/opencv-project:${{ matrix.tag }}
