name: 28544_deploy

on:
  workflow_run:
    workflows: ["28544_test"]
    types: ["completed"]

jobs:
  buildAndPush:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker build
        run: |
          docker build -t tilcica/sa3-cicd:latest .

      - name: docker push
        run: |
          docker push tilcica/sa3-cicd:latest
